server:
  port: 8000
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: demo-gateway
  cloud:
    gateway:
      routes:
        - id: demo-server
          uri: http://localhost:8080
          predicates:
            - Path=/demo/**
